/** Generated by YAKINDU Statechart Tools code generator. */
package practice1.lamp;

import practice1.IStatemachine;
import practice1.ITimerCallback;

public interface ILampStatemachine extends ITimerCallback,IStatemachine {
	public interface SCIUI {
	
		public void raiseSwitch();
		
		public void raiseFlash();
		
		public void setSCIUIOperationCallback(SCIUIOperationCallback operationCallback);
	
	}
	
	public interface SCIUIOperationCallback {
	
		public void turnOn();
		
		public void turnOff();
		
	}
	
	public SCIUI getSCIUI();
	
}
